install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 217002712
        modified: false
        timestamp: 0
    gameflow-patcher-lock: null
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_US"
        region: "NA"
    icon_version: 2
    last-valid-login-splash:
        theme: "worlds2019"
        version: "1.60"
    lcu-settings:
        accountId: 217002712
        modified: false
        timestamp: 0
    licensesAgreedTo:
        576F00F89F0C6BED5C0B5166E2D6D1F7: null
    login-remember-me:
        rememberMe: true
        username: "mykillingspree2"
    npe-splash:
        enableNewPlayerSplash: false
    patcher:
        client_migrated: true
        client_patcher_available: true
        client_patcher_migrated_time: "2019-06-18T02:23:21Z"
        game_migrated: true
        game_patcher_available: true
        game_patcher_migrated_time: "2019-05-06T22:19:07Z"
        locales:
        - "en_US"
        toggles:
            concurrent_manifest: 1028463294
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 217002712
        modified: false
        timestamp: 0
    riot-id-announcement-settings:
        accountId: 217002712
        modified: false
        timestamp: 0
    riotclient-upgrade:
        aux-environment: "live"
        installer-decrypt-key: "ZuV40vGHTGYoUCpx"
        installer-filename: "rc-win.enc"
        recovery-failures: 25
        seq-install-attempts: 0
        seq-success-count: 512
        success-count: 977
        total-install-attempts: 2
        uninstaller-repaired: true
        uninstaller-updated: true
        upgrade-ready: false
    rso-auth:
        install-identifier: "b4325080ad0c4446afca161170db7e13"
    splash:
        disableAnimation: true
    telemetry:
        fresh_installation: false
        installation_id: "7jjc4A=="
